from typing import Callable, Iterator, Self

import ludicrous
from ludicrous import (
    a,
    abbr,
    address,
    area,
    article,
    aside,
    audio,
    b,
    base,
    bdi,
    bdo,
    big,
    blockquote,
    body,
    br,
    button,
    canvas,
    caption,
    circle,
    cite,
    code,
    col,
    colgroup,
    data,
    datalist,
    dd,
    del_,
    details,
    dfn,
    dialog,
    div,
    dl,
    dt,
    em,
    embed,
    fieldset,
    figcaption,
    figure,
    footer,
    form,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    head,
    header,
    hr,
    hrgroup,
    html,
    i,
    iframe,
    img,
    input,
    ins,
    kbd,
    label,
    legend,
    li,
    line,
    link,
    main,
    map,
    mark,
    menu,
    meta,
    meter,
    nav,
    noscript,
    object,
    ol,
    optgroup,
    option,
    output,
    p,
    param,
    path,
    picture,
    polyline,
    pre,
    progress,
    q,
    rp,
    rt,
    ruby,
    s,
    samp,
    script,
    search,
    section,
    select,
    small,
    source,
    span,
    strong,
    sub,
    summary,
    sup,
    svg,
    table,
    tbody,
    td,
    template,
    textarea,
    tfoot,
    th,
    thead,
    time,
    title,
    tr,
    track,
    u,
    ul,
    var,
    video,
    wbr,
)

from .attrs import (
    AreaAttrs,
    AudioAttrs,
    BaseAttrs,
    BlockquoteAttrs,
    ButtonAttrs,
    CanvasAttrs,
    CircleAttrs,
    ColAttrs,
    DataAttrs,
    DelAttrs,
    DetailsAttrs,
    DialogAttrs,
    EmbedAttrs,
    FieldsetAttrs,
    FormAttrs,
    GlobalAttrs,
    HeadLinkAttrs,
    HtmlAttrs,
    HtmlTagAttrs,
    HyperlinkAttrs,
    IframeAttrs,
    ImgAttrs,
    InputAttrs,
    InsAttrs,
    LabelAttrs,
    LiAttrs,
    LineAttrs,
    MapAttrs,
    MetaAttrs,
    MeterAttrs,
    NoAttrs,
    ObjectAttrs,
    OlAttrs,
    OptgroupAttrs,
    OptionAttrs,
    OutputAttrs,
    ParamAttrs,
    PathAttrs,
    PolylineAttrs,
    ProgressAttrs,
    QAttrs,
    ScriptAttrs,
    SelectAttrs,
    SourceAttrs,
    StyleAttrs,
    SvgAttrs,
    TdAttrs,
    TextAreaAttrs,
    ThAttrs,
    TimeAttrs,
    TrackAttrs,
    VideoAttrs,
)
from .format import format_attrs
from .styles import (
    Theme,
    format_styles,
    from_components,
    from_loaded,
    get_default_theme,
)
from .styles.types import CSSProperties, GlobalStyles


class style(ludicrous.style, GlobalStyles):
    @classmethod
    def use(cls, styles: GlobalStyles | Callable[[Theme], GlobalStyles]) -> Self:
        return cls(styles)

    @classmethod
    def from_components(
        cls, *components: type[ludicrous.BaseElement], theme: Theme | None = None
    ) -> Self:
        return cls(from_components(*components, theme=theme), type="text/css")

    @classmethod
    def load(cls, cache: bool = False, theme: Theme | None = None) -> Self:
        return cls(from_loaded(cache=cache, theme=theme), type="text/css")

    def __getitem__(self, key: str | tuple[str, ...]) -> CSSProperties | GlobalStyles:
        return self.styles[key]

    def __iter__(self) -> Iterator[str | tuple[str, ...]]:
        return iter(self.styles.keys())

    def __len__(self) -> int:
        return len(self.styles)

    @property
    def theme(self) -> Theme:
        return self.context.get("theme", get_default_theme())

    @property
    def styles(self) -> GlobalStyles:
        if isinstance(self.children[0], str):
            return {}
        elif callable(self.children[0]):
            return self.children[0](self.theme)
        else:
            return self.children[0]

    @styles.setter
    def styles(self, value: GlobalStyles) -> None:
        self.children = (value,)

    def to_html(self) -> str:
        attributes = ""
        if formatted_attrs := format_attrs(type(self), self.attrs):
            attributes = f" {formatted_attrs}"

        if isinstance(self.children[0], str):
            css_styles = self.children[0]
        else:
            css_styles = format_styles(self.styles)

        return (
            f"<{self.html_name}{attributes}>\n"
            f"{css_styles}\n"
            f"</{self.html_name}>"
        )  # fmt: off


_ATTRS_MAPPING = {
    "a": HyperlinkAttrs,
    "abbr": GlobalAttrs,
    "address": GlobalAttrs,
    "area": AreaAttrs,
    "article": GlobalAttrs,
    "aside": GlobalAttrs,
    "audio": AudioAttrs,
    "b": GlobalAttrs,
    "base": BaseAttrs,
    "bdi": GlobalAttrs,
    "bdo": GlobalAttrs,
    "big": GlobalAttrs,
    "blockquote": BlockquoteAttrs,
    "body": GlobalAttrs,
    "br": GlobalAttrs,
    "button": ButtonAttrs,
    "canvas": CanvasAttrs,
    "caption": GlobalAttrs,
    "circle": CircleAttrs,
    "cite": GlobalAttrs,
    "code": GlobalAttrs,
    "col": ColAttrs,
    "colgroup": GlobalAttrs,
    "data": DataAttrs,
    "datalist": GlobalAttrs,
    "dd": GlobalAttrs,
    "del_": DelAttrs,
    "details": DetailsAttrs,
    "dfn": GlobalAttrs,
    "dialog": DialogAttrs,
    "div": GlobalAttrs,
    "dl": GlobalAttrs,
    "dt": GlobalAttrs,
    "em": GlobalAttrs,
    "embed": EmbedAttrs,
    "fieldset": FieldsetAttrs,
    "figcaption": GlobalAttrs,
    "figure": GlobalAttrs,
    "footer": GlobalAttrs,
    "form": FormAttrs,
    "h1": GlobalAttrs,
    "h2": GlobalAttrs,
    "h3": GlobalAttrs,
    "h4": GlobalAttrs,
    "h5": GlobalAttrs,
    "h6": GlobalAttrs,
    "head": NoAttrs,
    "header": GlobalAttrs,
    "hr": GlobalAttrs,
    "hrgroup": GlobalAttrs,
    "html": HtmlTagAttrs,
    "i": GlobalAttrs,
    "iframe": IframeAttrs,
    "img": ImgAttrs,
    "input": InputAttrs,
    "ins": InsAttrs,
    "kbd": GlobalAttrs,
    "label": LabelAttrs,
    "legend": GlobalAttrs,
    "li": LiAttrs,
    "line": LineAttrs,
    "link": HeadLinkAttrs,
    "main": GlobalAttrs,
    "map": MapAttrs,
    "mark": GlobalAttrs,
    "menu": GlobalAttrs,
    "meta": MetaAttrs,
    "meter": MeterAttrs,
    "nav": GlobalAttrs,
    "noscript": GlobalAttrs,
    "object": ObjectAttrs,
    "ol": OlAttrs,
    "optgroup": OptgroupAttrs,
    "option": OptionAttrs,
    "output": OutputAttrs,
    "p": GlobalAttrs,
    "param": ParamAttrs,
    "path": PathAttrs,
    "picture": GlobalAttrs,
    "polyline": PolylineAttrs,
    "pre": GlobalAttrs,
    "progress": ProgressAttrs,
    "q": QAttrs,
    "rp": GlobalAttrs,
    "rt": GlobalAttrs,
    "ruby": GlobalAttrs,
    "s": GlobalAttrs,
    "samp": GlobalAttrs,
    "script": ScriptAttrs,
    "search": GlobalAttrs,
    "section": GlobalAttrs,
    "select": SelectAttrs,
    "small": GlobalAttrs,
    "source": SourceAttrs,
    "span": GlobalAttrs,
    "strong": GlobalAttrs,
    "style": StyleAttrs,
    "sub": GlobalAttrs,
    "summary": GlobalAttrs,
    "sup": GlobalAttrs,
    "svg": SvgAttrs,
    "table": GlobalAttrs,
    "tbody": GlobalAttrs,
    "td": TdAttrs,
    "template": HtmlAttrs,
    "textarea": TextAreaAttrs,
    "tfoot": GlobalAttrs,
    "th": ThAttrs,
    "thead": GlobalAttrs,
    "time": TimeAttrs,
    "title": NoAttrs,
    "tr": GlobalAttrs,
    "track": TrackAttrs,
    "u": GlobalAttrs,
    "ul": GlobalAttrs,
    "var": GlobalAttrs,
    "video": VideoAttrs,
    "wbr": GlobalAttrs,
}


__all__ = (
    "a",
    "abbr",
    "address",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "bdi",
    "bdo",
    "big",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "circle",
    "cite",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del_",
    "details",
    "dfn",
    "dialog",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hr",
    "hrgroup",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "line",
    "link",
    "main",
    "map",
    "mark",
    "menu",
    "meta",
    "meter",
    "nav",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "path",
    "picture",
    "polyline",
    "pre",
    "progress",
    "q",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "script",
    "search",
    "section",
    "select",
    "small",
    "source",
    "span",
    "strong",
    "sub",
    "summary",
    "sup",
    "svg",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
)
