from collections.abc import Mapping, MutableMapping, Sequence
from typing import Any

class BaseElement:
    html_header: str | None
    html_name: str | None
    void_element: bool

    children: Sequence[Any]
    attrs: Mapping[str, Any]
    context: MutableMapping[str, Any]

    @property
    def text(self) -> str:
        """Get the text content of the element."""
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def is_simple(self) -> bool: ...
    def has_attributes(self) -> bool: ...
    def to_string(self) -> str: ...
    def to_html(self) -> str: ...

class div(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> div: ...

class span(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> span: ...

class main(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> main: ...

class p(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> p: ...

class a(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> a: ...

class br(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> br: ...

class button(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> button: ...

class label(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> label: ...

class td(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> td: ...

class th(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> th: ...

class tr(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> tr: ...

class thead(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> thead: ...

class tbody(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> tbody: ...

class tfoot(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> tfoot: ...

class table(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> table: ...

class li(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> li: ...

class ul(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> ul: ...

class ol(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> ol: ...

class dt(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> dt: ...

class dd(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> dd: ...

class dl(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> dl: ...

class section(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> section: ...

class input(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> input: ...

class output(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> output: ...

class legend(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> legend: ...

class option(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> option: ...

class optgroup(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> optgroup: ...

class select(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> select: ...

class textarea(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> textarea: ...

class fieldset(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> fieldset: ...

class form(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> form: ...

class img(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> img: ...

class svg(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> svg: ...

class circle(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> circle: ...

class line(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> line: ...

class path(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> path: ...

class polyline(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> polyline: ...

class b(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> b: ...

class i(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> i: ...

class s(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> s: ...

class u(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> u: ...

class strong(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> strong: ...

class em(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> em: ...

class mark(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> mark: ...

class del_(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> del_: ...

class ins(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> ins: ...

class header(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> header: ...

class big(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> big: ...

class small(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> small: ...

class code(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> code: ...

class pre(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> pre: ...

class cite(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> cite: ...

class blockquote(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> blockquote: ...

class abbr(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> abbr: ...

class h1(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> h1: ...

class h2(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> h2: ...

class h3(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> h3: ...

class h4(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> h4: ...

class h5(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> h5: ...

class h6(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> h6: ...

class title(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> title: ...

class link(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> link: ...

class script(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> script: ...

class noscript(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> noscript: ...

class meta(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> meta: ...

class head(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> head: ...

class body(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> body: ...

class footer(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> footer: ...

class html(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> html: ...

class iframe(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> iframe: ...

class article(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> article: ...

class address(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> address: ...

class caption(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> caption: ...

class col(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> col: ...

class colgroup(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> colgroup: ...

class area(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> area: ...

class aside(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> aside: ...

class source(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> source: ...

class audio(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> audio: ...

class base(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> base: ...

class bdi(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> bdi: ...

class bdo(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> bdo: ...

class canvas(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> canvas: ...

class data(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> data: ...

class datalist(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> datalist: ...

class details(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> details: ...

class dfn(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> dfn: ...

class dialog(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> dialog: ...

class embed(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> embed: ...

class figcaption(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> figcaption: ...

class figure(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> figure: ...

class hrgroup(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> hrgroup: ...

class hr(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> hr: ...

class kbd(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> kbd: ...

class map(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> map: ...

class menu(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> menu: ...

class meter(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> meter: ...

class nav(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> nav: ...

class object(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> object: ...

class param(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> param: ...

class picture(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> picture: ...

class progress(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> progress: ...

class q(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> q: ...

class rp(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> rp: ...

class rt(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> rt: ...

class ruby(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> ruby: ...

class samp(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> samp: ...

class search(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> search: ...

class sub(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> sub: ...

class summary(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> summary: ...

class sup(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> sup: ...

class template(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> template: ...

class time(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> time: ...

class track(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> track: ...

class var(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> var: ...

class video(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> video: ...

class wbr(BaseElement):
    def __new__(*children: Any, **attrs: Any) -> wbr: ...
