from typing import Unpack

from ludic.attrs import (
    AreaAttrs,
    AudioAttrs,
    BaseAttrs,
    BlockquoteAttrs,
    ButtonAttrs,
    CanvasAttrs,
    CircleAttrs,
    ColAttrs,
    DataAttrs,
    DelAttrs,
    DetailsAttrs,
    DialogAttrs,
    EmbedAttrs,
    FieldsetAttrs,
    FormAttrs,
    GlobalAttrs,
    HeadLinkAttrs,
    HtmlAttrs,
    HtmlTagAttrs,
    HyperlinkAttrs,
    IframeAttrs,
    ImgAttrs,
    InputAttrs,
    InsAttrs,
    LabelAttrs,
    LiAttrs,
    LineAttrs,
    MapAttrs,
    MetaAttrs,
    MeterAttrs,
    NoAttrs,
    ObjectAttrs,
    OlAttrs,
    OptgroupAttrs,
    OptionAttrs,
    OutputAttrs,
    ParamAttrs,
    PathAttrs,
    PolylineAttrs,
    ProgressAttrs,
    QAttrs,
    ScriptAttrs,
    SelectAttrs,
    SourceAttrs,
    SvgAttrs,
    TdAttrs,
    TextAreaAttrs,
    ThAttrs,
    TimeAttrs,
    TrackAttrs,
    VideoAttrs,
)
from ludic.types import (
    AnyChildren,
    ComplexChildren,
    NoChildren,
    PrimitiveChildren,
)
from ludicrous.base import Element

def div(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def span(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def main(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def p(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def a(*children: AnyChildren, **attrs: Unpack[HyperlinkAttrs]) -> Element: ...
def br(*children: NoChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def button(*children: AnyChildren, **attrs: Unpack[ButtonAttrs]) -> Element: ...
def label(*children: AnyChildren, **attrs: Unpack[LabelAttrs]) -> Element: ...
def td(*children: AnyChildren, **attrs: Unpack[TdAttrs]) -> Element: ...
def th(*children: AnyChildren, **attrs: Unpack[ThAttrs]) -> Element: ...
def tr(*children: ComplexChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def thead(*children: ComplexChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def tbody(*children: ComplexChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def tfoot(*children: ComplexChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def table(*children: ComplexChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def li(*children: AnyChildren, **attrs: Unpack[LiAttrs]) -> Element: ...
def ul(*children: ComplexChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def ol(*children: ComplexChildren, **attrs: Unpack[OlAttrs]) -> Element: ...
def dt(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def dd(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def dl(*children: ComplexChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def section(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def input(*children: NoChildren, **attrs: Unpack[InputAttrs]) -> Element: ...
def output(*children: NoChildren, **attrs: Unpack[OutputAttrs]) -> Element: ...
def legend(*children: PrimitiveChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def option(*children: PrimitiveChildren, **attrs: Unpack[OptionAttrs]) -> Element: ...
def optgroup(*children: AnyChildren, **attrs: Unpack[OptgroupAttrs]) -> Element: ...
def select(*children: AnyChildren, **attrs: Unpack[SelectAttrs]) -> Element: ...
def textarea(
    *children: PrimitiveChildren, **attrs: Unpack[TextAreaAttrs]
) -> Element: ...
def fieldset(*children: AnyChildren, **attrs: Unpack[FieldsetAttrs]) -> Element: ...
def form(*children: AnyChildren, **attrs: Unpack[FormAttrs]) -> Element: ...
def img(*children: NoChildren, **attrs: Unpack[ImgAttrs]) -> Element: ...
def svg(*children: AnyChildren, **attrs: Unpack[SvgAttrs]) -> Element: ...
def circle(*children: AnyChildren, **attrs: Unpack[CircleAttrs]) -> Element: ...
def line(*children: AnyChildren, **attrs: Unpack[LineAttrs]) -> Element: ...
def path(*children: AnyChildren, **attrs: Unpack[PathAttrs]) -> Element: ...
def polyline(*children: AnyChildren, **attrs: Unpack[PolylineAttrs]) -> Element: ...
def b(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def i(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def s(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def u(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def strong(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def em(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def mark(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def del_(*children: AnyChildren, **attrs: Unpack[DelAttrs]) -> Element: ...
def ins(*children: AnyChildren, **attrs: Unpack[InsAttrs]) -> Element: ...
def header(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def big(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def small(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def code(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def pre(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def cite(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def blockquote(*children: AnyChildren, **attrs: Unpack[BlockquoteAttrs]) -> Element: ...
def abbr(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def h1(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def h2(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def h3(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def h4(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def h5(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def h6(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def title(*children: PrimitiveChildren, **attrs: Unpack[NoAttrs]) -> Element: ...
def link(*children: NoChildren, **attrs: Unpack[HeadLinkAttrs]) -> Element: ...
def script(*children: PrimitiveChildren, **attrs: Unpack[ScriptAttrs]) -> Element: ...
def noscript(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def meta(*children: NoChildren, **attrs: Unpack[MetaAttrs]) -> Element: ...
def head(*children: AnyChildren, **attrs: Unpack[NoAttrs]) -> Element: ...
def body(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def footer(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def html(*children: AnyChildren, **attrs: Unpack[HtmlTagAttrs]) -> Element: ...
def iframe(*children: NoChildren, **attrs: Unpack[IframeAttrs]) -> Element: ...
def article(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def address(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def caption(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def col(*children: NoChildren, **attrs: Unpack[ColAttrs]) -> Element: ...
def colgroup(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def area(*children: NoChildren, **attrs: Unpack[AreaAttrs]) -> Element: ...
def aside(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def source(*children: NoChildren, **attrs: Unpack[SourceAttrs]) -> Element: ...
def audio(*children: AnyChildren, **attrs: Unpack[AudioAttrs]) -> Element: ...
def base(*children: NoChildren, **attrs: Unpack[BaseAttrs]) -> Element: ...
def bdi(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def bdo(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def canvas(*children: AnyChildren, **attrs: Unpack[CanvasAttrs]) -> Element: ...
def data(*children: AnyChildren, **attrs: Unpack[DataAttrs]) -> Element: ...
def datalist(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def details(*children: AnyChildren, **attrs: Unpack[DetailsAttrs]) -> Element: ...
def dfn(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def dialog(*children: AnyChildren, **attrs: Unpack[DialogAttrs]) -> Element: ...
def embed(*children: NoChildren, **attrs: Unpack[EmbedAttrs]) -> Element: ...
def figcaption(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def figure(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def hrgroup(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def hr(*children: NoChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def kbd(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def map(*children: AnyChildren, **attrs: Unpack[MapAttrs]) -> Element: ...
def menu(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def meter(*children: AnyChildren, **attrs: Unpack[MeterAttrs]) -> Element: ...
def nav(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def object(*children: AnyChildren, **attrs: Unpack[ObjectAttrs]) -> Element: ...
def param(*children: NoChildren, **attrs: Unpack[ParamAttrs]) -> Element: ...
def picture(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def progress(*children: AnyChildren, **attrs: Unpack[ProgressAttrs]) -> Element: ...
def q(*children: AnyChildren, **attrs: Unpack[QAttrs]) -> Element: ...
def rp(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def rt(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def ruby(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def samp(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def search(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def sub(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def summary(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def sup(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def template(*children: AnyChildren, **attrs: Unpack[HtmlAttrs]) -> Element: ...
def time(*children: AnyChildren, **attrs: Unpack[TimeAttrs]) -> Element: ...
def track(*children: NoChildren, **attrs: Unpack[TrackAttrs]) -> Element: ...
def var(*children: AnyChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
def video(*children: AnyChildren, **attrs: Unpack[VideoAttrs]) -> Element: ...
def wbr(*children: NoChildren, **attrs: Unpack[GlobalAttrs]) -> Element: ...
